// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRecipes.DataContext.Recipes;

#nullable disable

namespace SmartRecipes.DataContext.Migrations.Recipes
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20240304161747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Category", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Image", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Ingredient", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.IngredientAmountForRecipe", b =>
                {
                    b.Property<string>("IngredientID")
                        .HasColumnType("text");

                    b.Property<string>("RecipeID")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("0 кг");

                    b.HasKey("IngredientID", "RecipeID");

                    b.HasIndex("RecipeID");

                    b.ToTable("IngredientAmounts");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.IngredientPriceForShop", b =>
                {
                    b.Property<string>("AvailableIngredientsID")
                        .HasColumnType("text");

                    b.Property<string>("ShopsWhereAvailableID")
                        .HasColumnType("text");

                    b.Property<string>("IngredientID")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ShopID")
                        .HasColumnType("text");

                    b.HasKey("AvailableIngredientsID", "ShopsWhereAvailableID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("ShopID");

                    b.HasIndex("ShopsWhereAvailableID");

                    b.ToTable("IngredientPrices");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Recipe", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipeDescription")
                        .IsRequired()
                        .HasMaxLength(6400)
                        .HasColumnType("character varying(6400)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<float>("TimeToCook")
                        .HasColumnType("real");

                    b.Property<int>("TimesDisliked")
                        .HasColumnType("integer");

                    b.Property<int>("TimesLiked")
                        .HasColumnType("integer");

                    b.Property<int>("TimesVisited")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Shop", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ID");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Image", b =>
                {
                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Recipe", "RecipeWhereUsed")
                        .WithOne("RecipeImage")
                        .HasForeignKey("SmartRecipes.DataContext.Recipes.Models.Image", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeWhereUsed");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.IngredientAmountForRecipe", b =>
                {
                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Recipe", "Recipe")
                        .WithMany("IngredientsAmounts")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Ingredient", "Ingredient")
                        .WithMany("AmountsForRecipes")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.IngredientPriceForShop", b =>
                {
                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Ingredient", null)
                        .WithMany("PriceInShops")
                        .HasForeignKey("AvailableIngredientsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientID");

                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopID");

                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Shop", null)
                        .WithMany("IngredientPrices")
                        .HasForeignKey("ShopsWhereAvailableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Recipe", b =>
                {
                    b.HasOne("SmartRecipes.DataContext.Recipes.Models.Category", "Category")
                        .WithMany("RecipesWhereUsed")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Category", b =>
                {
                    b.Navigation("RecipesWhereUsed");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Ingredient", b =>
                {
                    b.Navigation("AmountsForRecipes");

                    b.Navigation("PriceInShops");
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Recipe", b =>
                {
                    b.Navigation("IngredientsAmounts");

                    b.Navigation("RecipeImage")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRecipes.DataContext.Recipes.Models.Shop", b =>
                {
                    b.Navigation("IngredientPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
